### ISSUE TITLE
Stop depending on Item Tweaker mod

### ISSUE THREAD

**Issue by matshou** [cocolabs/pz-liquid-overhaul#2]
We should find a way not to depend on this mod, as it introduces potential problems if the mod becomes outdated.

**Comment by Konijima** [comment]
Alright so here what I did and it works but only for new items.

```lua
local items = {
	Coco_WaterGallonEmpty = { "CocoLiquidOverhaulItems.Coco_WaterGallonEmpty", "Coco_Liquid_Container" },
	Coco_WaterGallonFull = { "CocoLiquidOverhaulItems.Coco_WaterGallonFull", "Coco_Liquid_Container" },
	Coco_WaterGallonPetrol = { "CocoLiquidOverhaulItems.Coco_WaterGallonPetrol", "Coco_Liquid_Container" },
};

local function TweakItems()
	
	for k, v in pairs(items) do
		local item = ScriptManager.instance:getItem(v[1]);
		if item ~= nil then
			item:DoParam("displaycategory".." = " .. v[2]);
		end;
	end;
	
end;

Events.OnLoad.Add(TweakItems);
```

### DoParam() seems to works but here is the problem:
```lua
item:DoParam("displaycategory".." = " .."MyCustomCategory");
```
  
**1:** Load in the game.
**2:** Spawn an item.
**3:** Item category is custom.
**4:** Quit to main menu.
**5:** Load back in the game.
**6:** Existing item's category (in inventory) is reset back to normal "Item" category.
**7:** Spawn a new item (same item).
**8:** If you still have the old item in inventory the category won't change for the old and new one.
**9:** If you remove that item from inventory and spawn it a new item one, then category is custom for the new one.

Same problem apply to items on the ground.
So what I am thinking is that we need to find how to update  Existing items in the world with the custom category when the game loads.

**Comment by Konijima** [comment]
Tchernobill posted on steam a solution that i tested and it's working.
There might be a downside but it's not really concerning.

> From Tchernobill     
>  replace
>  **Events.OnLoad.Add(TweakItems);**
>  by
>  **Events.OnGameBoot.Add(TweakItems)**
>  This will do what you expect.
>  But as a consequence, activating or deactivating the mod will require to re-start the game for the effect to take place.

```lua
local items = {
	Coco_WaterGallonEmpty = {"CocoLiquidOverhaulItems.Coco_WaterGallonEmpty", "Coco_Liquid_Container"},
	Coco_WaterGallonFull = {"CocoLiquidOverhaulItems.Coco_WaterGallonFull", "Coco_Liquid_Container"},
	Coco_WaterGallonPetrol = {"CocoLiquidOverhaulItems.Coco_WaterGallonPetrol", "Coco_Liquid_Container"}
}

local function CocoLiquidOverhaul_TweakItems()
	for k, v in pairs(items) do
		local item = ScriptManager.instance:getItem(v[1])
		if item ~= nil then
			item:DoParam("displaycategory" .. " = " .. v[2])
		end
	end
end

-- OnGameBoot instead on OnLoad does fix the category name reset
Events.OnGameBoot.Add(CocoLiquidOverhaul_TweakItems)
--Events.OnLoad.Add(CocoLiquidOverhaul_TweakItems);
```

I will close the issue for now it will be available in the next update on the workshop.
If we find better or an other issue we can re-open.
